name: Update conformance test reports

on:

jobs:
  update:
    name: Update conformance test reports
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          path: reference-checker
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run Conformance Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: conformanceTest conformanceTestOnSamples
        env:
          JSPECIFY_CONFORMANCE_TEST_MODE: write
      - name: Maybe create PR
        run: |
          if git status --porcelain tests/*-report.txt | egrep -q '^M'; then
            git checkout -B update-conformance-test-reports
            git commit -m "Update conformance test reports." tests/ConformanceTest*-report.txt
            git push
            gh pr create --base main --title "Update conformance test reports."  --body ""
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

